
class EventRecorder
  MAXQUEUE: 100

  # Initializes the event recorder
  #
  # @param seed The seed generated by Math.seedrandom()
  constructor: (@seed, @id) ->
    @seed = @seed + "endseed\n"
    $.ajax
      type: 'POST'
      url: '../server/eventLogger.php'
      data:
        id: @id
        seed: @seed
        events: [{time: window.innerWidth, event: window.innerHeight, param: null}]
      success: (data) ->
      dataType: 'json'
      async: true

    @_queue = []

  # records the given event
  #
  # @param [String] event The name of the event to record
  # @param [Object] e The data that goes with the event
  recordEvent: (event, e) ->
    #console.log(event)
    @_queue.push({time: timeSinceStart(), event: event, param: e})
    if @_queue.length > @MAXQUEUE
      @send()

  send: (async=true) ->
    $.ajax
      type: 'POST'
      url: '../server/eventLogger.php'
      data:
        id: @id
        seed: @seed
        events: @_queue
      success: (data) ->
      dataType: 'json'
      async: async
    @_queue = []
